### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by rebeccaannwong** [rebeccaannwong/hyperlapse#1]
@harimohanraj89 @harimohanraj89 

Attempting to use geocoder gem, created locations table.

Running into error when i do this in command line:
Rake aborted
rails generate migration AddLatitudeAndLongitudeToLocation latitude:float longitude:float

My hyperlapse migration runs but not my locations migration

**Comment by harimohanraj89** [comment]
- What is the entire error that you received?
- Did you receive the error when running `rails generate migration...` or when running `rake db:migrate`
- What is the code inside the relevant migration files? Push your code and tell me which files in which branch to take a look at
- Are you sure that your locations table exists? (Check your schema.rb file)

**Comment by rebeccaannwong** [comment]
i think i am going to delete the entire file. My schema was not showing and all the code I've been working on is in separate files which I am trying to pull together right now

$ rake db:migrate
== 20141215153529 CreateHyperlapse: migrating =================================
-- create_table(:hyperlapses)
   -> 0.0589s
== 20141215153529 CreateHyperlapse: migrated (0.0591s) ========================

== 20141218144836 AddLatitudeAndLongitudeToLocation: migrating ================
-- add_column(:locations, :latitude, :float)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "locations" does not exist
: ALTER TABLE "locations" ADD COLUMN "latitude" float/Users/rebeccaannwong/Repos/hyperlapse/hyperlapse/db/migrate/20141218144836_add_latitude_and_longitude_to_location.rb:3:in `change'
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "locations" does not exist
: ALTER TABLE "locations" ADD COLUMN "latitude" float
/Users/rebeccaannwong/Repos/hyperlapse/hyperlapse/db/migrate/20141218144836_add_latitude_and_longitude_to_location.rb:3:in`change'
PG::UndefinedTable: ERROR:  relation "locations" does not exist
/Users/rebeccaannwong/Repos/hyperlapse/hyperlapse/db/migrate/20141218144836_add_latitude_and_longitude_to_location.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by harimohanraj89** [comment]
Do you have a migration to create a locations table? Your error says that you do not have a locations table.

**Comment by harimohanraj89** [comment]
Closing this after our conversation.
