### ISSUE TITLE
Hyperlapse and Location Routes 

### ISSUE THREAD

**Issue by rebeccaannwong** [rebeccaannwong/hyperlapse#3]
@htella @harimohanraj89 @DrRobotmck 

Confused when building my routes :/ Would like to clarify certain things about the Hyperlapse. 

I want the user to be able to save hyperlapse videos/latitude and longtitude of hyperlapse so that they can access previous searches.

Do I need a hyperlapse table? Or can I just use a locations table? 

When I drew out my ERD, I assumed I would need a hyperlapse table?

Eg: For my location routes:
  get 'locations' => 'locations#index'
  get 'locations/:id' => 'hyperlapse#show'

or

  get 'locations' => 'locations#index'
  get 'locations/:id' => 'locations#show'

**Comment by htella** [comment]
got this one.
